services:
  mongo:
    image: mongo:4.4.5
    container_name: database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - ${VOL_DIR}/scraper:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis:7.4.0-alpine
    container_name: bull_redis
    command: ['redis-server', '--save', '60', '1', '--loglevel', 'warning']
    ports:
      - '6379:6379'
    volumes:
      - ${VOL_DIR}/bull_redis:/data

  postgres:
    image: postgres:16
    container_name: revolico_postgres
    restart: always
    environment:
      POSTGRES_USER: revolico
      POSTGRES_PASSWORD: revolico
      POSTGRES_DB: revolico
    ports:
      - '5432:5432'
    volumes:
      - ${VOL_DIR}/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U revolico']
      interval: 10s
      timeout: 5s
      retries: 5
