version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - ${VOL_DIR}/scraper:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis:7.4.0-alpine
    container_name: bull_redis
    command: ['redis-server', '--save', '60', '1', '--loglevel', 'warning']
    ports:
      - '6379:6379'
    volumes:
      - ${VOL_DIR}/bull_redis:/data
