export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  DASHBOARD: '/dashboard',
  ALARMS: '/alarms',
  ALARM_NEW: '/alarms/new',
  ALARM_DETAIL: (id: string) => `/alarms/${id}`,
  ALARM_EDIT: (id: string) => `/alarms/${id}/edit`,
  BOTS: '/bots',
  NOTIFICATIONS: '/notifications',
  ACCOUNT: '/account',
  PROFILE: '/profile',
  ONBOARDING: '/onboarding',
} as const;
