/**
 * Fallback word-list values for rule-based attribute extraction.
 *
 * These are the canonical defaults used when the Rule database table is
 * empty or unreachable. They are also the seed data loaded by `prisma/seed.ts`.
 *
 * Six categories are externalised (word-list only). Regex-based patterns
 * (rooms, bathrooms, garage, floors, storage, RAM, originalPrice, delivery)
 * remain as code in RuleBasedExtractorService.
 */
export const FALLBACK_RULES: Record<string, string[]> = {
  brands: [
    'apple',
    'samsung',
    'huawei',
    'xiaomi',
    'motorola',
    'lg',
    'sony',
    'nokia',
    'lenovo',
    'dell',
    'hp',
    'asus',
    'acer',
    'toshiba',
    'canon',
    'nikon',
    'bosch',
    'whirlpool',
    'midea',
    'haier',
    'panasonic',
    'philips',
    'daewoo',
    'electrolux',
    'toyota',
    'hyundai',
    'kia',
    'peugeot',
    'audi',
    'bmw',
    'mercedes',
    'volkswagen',
    'nissan',
    'mitsubishi',
    'suzuki',
    'yamaha',
    'honda',
  ],
  conditions: [
    'perfecto estado',
    'buen estado',
    'mal estado',
    'todo de lujo',
    'muy buena',
    'gran rebaja',
    'super oferta',
    'como nuevo',
    'poco uso',
    'sin uso',
    'excelente',
    'exclusiva',
    'exclusivo',
    'oportunidad',
    'impecable',
    'hermosa',
    'hermoso',
    'precioso',
    'reacondicionado',
    'restaurado',
    'reparado',
    'regular',
    'danado',
    'defecto',
    'nuevo',
    'sellado',
    'rebaja',
    'oferta',
    'ideal',
    'lujo',
    'roto',
  ],
  colors: [
    'space gray',
    'starlight',
    'champagne',
    'turquesa',
    'plateado',
    'midnight',
    'grafito',
    'celeste',
    'violeta',
    'crema',
    'morado',
    'naranja',
    'amarillo',
    'marron',
    'beige',
    'coral',
    'dorado',
    'blanco',
    'negro',
    'verde',
    'rojo',
    'azul',
    'gris',
    'rosa',
    'pink',
    'gold',
    'blue',
    'red',
    'silver',
    'green',
    'black',
    'white',
    'purple',
    'yellow',
  ],
  propertyTypes: [
    'propiedad horizontal',
    'apartamento',
    'casa independiente',
    'biplanta',
    'triplanta',
    'casona',
    'finca',
    'hostal',
    'apto',
    'casa',
    'cuarto',
    'propiedad',
  ],
  locations: [
    'nuevo vedado',
    'centro habana',
    'la habana vieja',
    'habana vieja',
    'arroyo naranjo',
    'san miguel del padron',
    'santos suarez',
    'santa marta',
    'buena vista',
    'casino deportivo',
    'miramar',
    'vedado',
    'marianao',
    'lawton',
    'playa',
    'varadero',
    'santiago de cuba',
    'camaguey',
    'holguin',
    'santa clara',
    'cienfuegos',
    'pinar del rio',
    'matanzas',
    'guanabacoa',
    'regla',
    'cerro',
    'diez de octubre',
    'plaza de la revolucion',
    'habana del este',
    'boyeros',
    'cotorro',
    'lisa',
    'san jose de las lajas',
    'guines',
    'artemisa',
    'mayabeque',
    'bauta',
    'caimito',
    'guanajay',
    'mariel',
    'san antonio de los banos',
    'guira de melena',
    'alquizar',
    'batabano',
    'quibican',
    'jaruco',
    'madruga',
    'san nicolas',
    'nueva paz',
    'santa cruz del norte',
    'bejucal',
    'la salud',
    'melena del sur',
  ],
  warrantyKeywords: ['garantia', 'factura', 'con garantia', 'tiene garantia', 'con factura'],
};
