export const TAG = {
  AUTH: 'Auth',
  ACCOUNTS: 'Accounts',
  USERS: 'Users',
  PLANS: 'Plans',
  SUBSCRIPTIONS: 'Subscriptions',
  ALARMS: 'Alarms',
  NOTIFICATIONS: 'Notifications',
  PRODUCTS: 'Products',
  SCRAPING: 'Scraping',
  ADMIN: 'Admin',
  BOTS: 'Bots',
  // Admin subgroup tags
  ADMIN_PRODUCTS: 'Admin - Products',
  ADMIN_DASHBOARD: 'Admin - Dashboard',
  ADMIN_QUEUES: 'Admin - Queues',
  ADMIN_ACCOUNTS: 'Admin - Accounts',
  ADMIN_ROLES: 'Admin - Roles',
  ADMIN_RULES: 'Admin - Rules',
  ADMIN_SCHEDULES: 'Admin - Scraping Schedules',
  ACCOUNT_MANAGEMENT: 'Account Management',
} as const;

export const API_TAGS = [
  { name: TAG.AUTH, description: 'Authentication endpoints' },
  { name: TAG.ACCOUNTS, description: 'Account management and registration' },
  { name: TAG.USERS, description: 'User management within an account' },
  { name: TAG.PLANS, description: 'Subscription plan management' },
  { name: TAG.SUBSCRIPTIONS, description: 'Account subscription management' },
  { name: TAG.ALARMS, description: 'Price-change alarm management' },
  { name: TAG.NOTIFICATIONS, description: 'Alarm notification management' },
  { name: TAG.PRODUCTS, description: 'Customer-facing product catalog' },
  { name: TAG.SCRAPING, description: 'Product scraping job management' },
  { name: TAG.ADMIN, description: 'Super-admin endpoints' },
  { name: TAG.BOTS, description: 'WhatsApp / Telegram bot account linking' },
  {
    name: TAG.ACCOUNT_MANAGEMENT,
    description: 'Account self-management: password reset, email verification, refresh tokens, deactivation',
  },
  { name: TAG.ADMIN_PRODUCTS, description: 'Admin product management' },
  { name: TAG.ADMIN_DASHBOARD, description: 'Admin dashboard and health checks' },
  { name: TAG.ADMIN_QUEUES, description: 'Admin queue introspection' },
  { name: TAG.ADMIN_ACCOUNTS, description: 'Admin account management' },
  { name: TAG.ADMIN_ROLES, description: 'Admin role management' },
  { name: TAG.ADMIN_RULES, description: 'Admin rule-based extractor pattern management' },
  { name: TAG.ADMIN_SCHEDULES, description: 'Admin automated scraping schedule management' },
];
