import { injectable } from 'inversify';

// ---- public interfaces -----------------------------------------------------

/**
 * Token usage reported by the LLM provider via the AI SDK.
 * Captured from `result.usage` in {@link extractKeywords}.
 */
export interface ILlmUsage {
  promptCacheHitTokens: number;
  promptCacheMissTokens: number;
  completionTokens: number;
}

/**
 * Immutable snapshot returned by {@link EnrichmentMetricsService.getSnapshot}.
 * All rates are 0–1. Denominators of zero produce a rate of 0.
 */
export interface IEnrichmentMetricsSnapshot {
  /** ISO-8601 timestamp of when the service started accumulating. */
  startedAt: string;
  /** Total number of {@link ProductService.enrichProduct} invocations. */
  totalEnrichments: number;
  /** How many enrichments were skipped because the description hash matched. */
  enrichmentHashSkips: number;
  /** skips / total (0 if total=0). */
  enrichmentHashSkipRate: number;

  /** How many times the rule-based extractor reached confidence ≥ 0.4. */
  ruleHighConfidence: number;
  /** ruleHits / (total - skips). Denominator of zero → 0. */
  ruleHighConfidenceRate: number;

  /** KeywordsCache hits (memory or MongoDB). */
  cacheHits: number;
  /** KeywordsCache misses (both layers). */
  cacheMisses: number;
  /** hits / (hits + misses). Denominator of zero → 0. */
  cacheHitRate: number;

  /** Successful LLM calls. */
  llmCalls: number;
  /** Failed LLM calls (network error, timeout, bad response). */
  llmFailures: number;
  /** failures / calls. Denominator of zero → 0. */
  llmFailureRate: number;

  /** Cumulative prompt tokens served from the LLM provider's cache. */
  llmPromptCacheHitTokens: number;
  /** Cumulative prompt tokens NOT served from cache (had to be recomputed). */
  llmPromptCacheMissTokens: number;
  /** Cumulative completion tokens generated by the LLM. */
  llmCompletionTokens: number;
  /** hitTokens / (hitTokens + missTokens). Denominator of zero → 0. */
  llmCacheHitRate: number;

  /**
   * Estimated USD saved via LLM prompt caching.
   * Formula: (promptCacheHitTokens / 1_000_000) * costPerMillionTokens.
   * 0 if `LLM_COST_PER_MILLION_TOKENS` is not set.
   */
  estimatedSavingsUSD: number;
  /** Price per million tokens used for the savings calculation (from env). */
  costPerMillionTokens: number;
}

// ---- service ----------------------------------------------------------------

/**
 * In-memory (non-persisted) counter service for the enrichment pipeline.
 *
 * Tracks every decision point in the 4-layer pipeline so operators can
 * monitor cache effectiveness and LLM token consumption via the admin API.
 *
 * **Thread safety**: Node.js is single-threaded; `++` on Number is safe.
 * Counters reset on process restart.
 *
 * @class EnrichmentMetricsService
 */
@injectable()
export class EnrichmentMetricsService {
  private readonly _startedAt: Date = new Date();

  // enrichmentHash guard
  private _totalEnrichments = 0;
  private _enrichmentHashSkips = 0;

  // rule-based extractor
  private _ruleHighConfidence = 0;

  // keywords cache
  private _cacheHits = 0;
  private _cacheMisses = 0;

  // LLM
  private _llmCalls = 0;
  private _llmFailures = 0;
  private _llmPromptCacheHitTokens = 0;
  private _llmPromptCacheMissTokens = 0;
  private _llmCompletionTokens = 0;

  // ---- public recorders -----------------------------------------------------

  /** Call once at the start of every {@link ProductService.enrichProduct}. */
  public recordEnrichment(): void {
    this._totalEnrichments++;
  }

  /** Call when enrichment is skipped because the description hash matches. */
  public recordEnrichmentHashSkip(): void {
    this._enrichmentHashSkips++;
  }

  /** Call when rule-based extraction confidence ≥ 0.4 (skips cache + LLM). */
  public recordRuleHighConfidence(): void {
    this._ruleHighConfidence++;
  }

  /** Call on KeywordsCache hit. */
  public recordCacheHit(): void {
    this._cacheHits++;
  }

  /** Call on KeywordsCache miss (will proceed to LLM). */
  public recordCacheMiss(): void {
    this._cacheMisses++;
  }

  /** Call after a successful LLM call with the usage stats from the provider. */
  public recordLlmCall(usage: ILlmUsage): void {
    this._llmCalls++;
    this._llmPromptCacheHitTokens += usage.promptCacheHitTokens;
    this._llmPromptCacheMissTokens += usage.promptCacheMissTokens;
    this._llmCompletionTokens += usage.completionTokens;
  }

  /** Call when an LLM call fails (network error, timeout, bad response). */
  public recordLlmFailure(): void {
    this._llmFailures++;
  }

  // ---- snapshot -------------------------------------------------------------

  /**
   * Returns an immutable snapshot of all counters and computed rates.
   * Safe to call from any thread/context — reads are non-mutating copies.
   *
   * @returns {IEnrichmentMetricsSnapshot} Current metrics snapshot.
   */
  public getSnapshot(): IEnrichmentMetricsSnapshot {
    const total = this._totalEnrichments;
    const nonSkipped = total - this._enrichmentHashSkips;
    const cost = this._readCostPerMillion();

    return {
      startedAt: this._startedAt.toISOString(),
      totalEnrichments: total,

      enrichmentHashSkips: this._enrichmentHashSkips,
      enrichmentHashSkipRate: total > 0 ? this._enrichmentHashSkips / total : 0,

      ruleHighConfidence: this._ruleHighConfidence,
      ruleHighConfidenceRate: nonSkipped > 0 ? this._ruleHighConfidence / nonSkipped : 0,

      cacheHits: this._cacheHits,
      cacheMisses: this._cacheMisses,
      cacheHitRate: this._cacheHits + this._cacheMisses > 0 ? this._cacheHits / (this._cacheHits + this._cacheMisses) : 0,

      llmCalls: this._llmCalls,
      llmFailures: this._llmFailures,
      llmFailureRate: this._llmCalls > 0 ? this._llmFailures / this._llmCalls : 0,

      llmPromptCacheHitTokens: this._llmPromptCacheHitTokens,
      llmPromptCacheMissTokens: this._llmPromptCacheMissTokens,
      llmCompletionTokens: this._llmCompletionTokens,
      llmCacheHitRate:
        this._llmPromptCacheHitTokens + this._llmPromptCacheMissTokens > 0
          ? this._llmPromptCacheHitTokens / (this._llmPromptCacheHitTokens + this._llmPromptCacheMissTokens)
          : 0,

      estimatedSavingsUSD: cost > 0 ? (this._llmPromptCacheHitTokens / 1_000_000) * cost : 0,
      costPerMillionTokens: cost,
    };
  }

  /** Resets all counters to zero. Intended for tests. */
  public reset(): void {
    this._totalEnrichments = 0;
    this._enrichmentHashSkips = 0;
    this._ruleHighConfidence = 0;
    this._cacheHits = 0;
    this._cacheMisses = 0;
    this._llmCalls = 0;
    this._llmFailures = 0;
    this._llmPromptCacheHitTokens = 0;
    this._llmPromptCacheMissTokens = 0;
    this._llmCompletionTokens = 0;
  }

  // ---- private -------------------------------------------------------------

  private _readCostPerMillion(): number {
    const raw = process.env.LLM_COST_PER_MILLION_TOKENS?.trim();
    if (!raw) return 0;
    const n = Number(raw);
    return Number.isFinite(n) && n >= 0 ? n : 0;
  }
}
